// MSXgl | Raw files definitions generated by the Build tool

#define TILES_BIN_SEG 	32
#define TILES_BIN_REL 	0x0000
#define TILES_BIN_ABS 	0x40000
#define TILES_BIN_SIZE	0x7000

#define HERO_BIN_SEG 	40
#define HERO_BIN_REL 	0x0000
#define HERO_BIN_ABS 	0x50000
#define HERO_BIN_SIZE	0x42000

#define ORC_BIN_SEG 	76
#define ORC_BIN_REL 	0x0000
#define ORC_BIN_ABS 	0x98000
#define ORC_BIN_SIZE	0xA000

#define ITEMS16_BIN_SEG 	82
#define ITEMS16_BIN_REL 	0x0000
#define ITEMS16_BIN_ABS 	0xA4000
#define ITEMS16_BIN_SIZE	0x2000

#define ARMOR32_BIN_SEG 	83
#define ARMOR32_BIN_REL 	0x0000
#define ARMOR32_BIN_ABS 	0xA6000
#define ARMOR32_BIN_SIZE	0x2000
