// Generated by compose_enemies.py - painted box per frame {xoff,yoff,w,h}
const unsigned char g_OrcBox[6][4] = {
	{9,1,29,47},
	{8,1,31,47},
	{0,19,47,29},
	{9,1,29,47},
	{8,1,31,47},
	{0,19,47,29},
};
