// Generated by compose_enemies.py - painted box per frame {xoff,yoff,w,h}
const unsigned char g_OrcBox[6][4] = {
	{6,1,39,47},
	{9,1,29,47},
	{0,19,47,29},
	{3,1,39,47},
	{10,1,29,47},
	{0,19,47,29},
};
